### ISSUE TITLE
QueryDirectory Request (0x0e)

### ISSUE THREAD

**Issue by jlee-r7** [rapid7/smb2#25]
https://msdn.microsoft.com/en-us/library/cc246551.aspx

Wireshark calls this "Find Request". https://wiki.wireshark.org/SMB2/Find

> The Find response might not return the full list of files in a single packet so the client must loop on this command until the server responds with `STATUS_NO_MORE_FILES`

**Comment by jlee-r7** [comment]
Of the existing tickets, this and #26 are probably the two that require the least knowledge of the code and protocol to get into.

**Comment by wvu-r7** [comment]
Thanks!
